window.onload = function start() {
    var quote = fetchQuote();
    document.getElementById('quote').innerHTML = quote.quote;
    document.getElementById('author').innerHTML = "- " + quote.author;
}

function fetchQuote() {
    var quotes = [
        {quote: 'Be kind whenever possible. It is always possible.', author: '14th Dalai Lama'},
        {quote: 'Our prime purpose in this life is to help others. And if you can\'t help them, at least don\'t hurt them.', author: '14th Dalai Lama'},
        {quote: 'This is my simple religion. There is no need for temples; no need for complicated philosophy. Our own brain, our own heart is our temple; the philosophy is kindness.', author: '14th Dalai Lama'},
        {quote: 'Happiness is not something ready made. It comes from your own actions.', author: '14th Dalai Lama'},
        {quote: 'My religion is very simple. My religion is kindness.', author: '14th Dalai Lama'},
        {quote: 'If you want others to be happy, practice compassion. If you want to be happy, practice compassion.', author: '14th Dalai Lama'},
        {quote: 'Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.', author: '14th Dalai Lama'},
        {quote: 'We can never obtain peace in the outer world until we make peace with ourselves.', author: '14th Dalai Lama'},
        {quote: 'In the practice of tolerance, one\'s enemy is the best teacher.', author: '14th Dalai Lama'},
        {quote: 'We can live without religion and meditation, but we cannot survive without human affection.', author: '14th Dalai Lama'},
        {quote: 'The Dharma is the best way of using your life', author: 'Dilgo Khyentse Rinpoche'},
        {quote: 'Cultivating a close, warm-hearted feeling for others automatically puts our mind at ease.', author: '14th Dalai Lama'},
        {quote: 'Smiling is very important. If we are not able to smile, then the world will not have peace. It is not by going out for a demonstration against nuclear missiles that we can bring about peace. It is with our capacity of smiling, breathing, and being peace that we can make peace.', author: 'Thich Nhat Hanh'},
        {quote: 'The ultimate definition of bravery is not being afraid of who you are.', author: 'Chögyam Trungpa Rinpoche'},
        {quote: 'Just as the great ocean has one taste, the taste of salt, so also this teaching and discipline has one taste, the taste of liberation.', author: 'Buddha'},
        {quote: 'Breathing in, I see myself as still water.<br />Breathing out, I reflect things as they are.', author: 'Thich Nhat Hanh'},
        {quote: 'Generosity is the most natural outward expression of an inner attitude of compassion and loving-kindness.', author: '14th Dalai Lama'},
        {quote: 'By eliminating the self-pitying imagination of ego, you go beyond fear. All fear and other self-pitying emotions come from holding a self-pitying image of yourself.', author: 'Lama Yeshe'},
        {quote: 'Death could come any minute so transform your life into dharma.', author: 'Lama Zopa Rinpoche'},
        {quote: 'Like the illusory face of this appearing world,<br />The movement of mind is not touched by artifice;<br />It is not altered by action, freedom, or realization.<br />To remain in the depths of mind free of reference<br />Is known as mahamudra.', author: '17th Karmapa'},
        {quote: 'Meditation is a uniquely personal process, and no two people\'s experience is alike.', author: 'Mingyur Rinpoche'},
        {quote: 'Our ultimate essence and our ultimate primordial nature is limitless freedom.', author: 'Tai Situ Rinpoche'},
        {quote: 'Our life passes, and the fact that it can end at any moment means we are in a most precarious and dangerous situation.', author: 'Tulku Urgyen Rinpoche'},
        {quote: 'A learned person will become noble only when he or she has put into practice what has been learned, instead of just mere words.', author: '14th Dalai Lama'},
        {quote: 'It is easy enough to be friendly to one\'s friends. But to befriend the one who regards himself as your enemy is the quintessence of true religion. The other is mere business.', author: 'Mahatma Gandhi'},
        {quote: 'There\'s no difference between what is seen and the mind that sees it.', author: 'Mingyur Rinpoche'},
        {quote: 'It is because of bodhicitta that one gives up<br />the pleasure of meditative concentration,<br />and in order to relieve others of their suffering<br />goes down to the deepest hell as if into a pleasure park.', author: 'Khunu Rinpoche'},
        {quote: 'Virtues are acquired through endeavor,<br />Which rests wholly upon yourself.<br />So, to praise others for their virtues<br />Can but encourage one\'s own efforts.', author: 'Nagarjuna'},
        {quote: 'Clouds draw water from the ocean to fall as rain on the earth<br />And there is neither increase nor decrease;<br />Just so, reality remains unaltered like the pure sky.', author: 'Saraha'},
        {quote: 'When another person makes you suffer, it is because he suffers deeply within himself, and his suffering is spilling over. He does not need punishment; he needs help. That\'s the message he is sending.', author: 'Thich Nhat Hanh'},
        {quote: 'Meditation is not on the level of the object but on that of the subject – you are the business of your meditation.', author: 'Lama Yeshe'},
        {quote: 'If you let go a little, you will have a little peace. If you let go a lot, you will have a lot of peace. If you let go completely, you will have complete peace.', author: 'Ajahn Chah'},
        {quote: 'There\'s a reason you can learn from everything: you have basic wisdom, basic intelligence, and basic goodness.', author: 'Pema Chödrön'},
        {quote: 'Why is compassion of foremost importance in the Buddha\'s teachings? Because it is the root of all the vastness and profundity of the bodhisattva path. Compassion is the awakened heart itself.', author: 'Dilgo Khyentse Rinpoche'},
        {quote: 'Developing compassion is the most fruitful way of “getting even” with people who make you angry.', author: 'Chögyam Trungpa Rinpoche'},
        {quote: 'The sun of real happiness shines in your life when you start to cherish others.', author: 'Lama Zopa Rinpoche'},
        {quote: 'Samsara is to see fault in others.', author: 'Tilopa'},
        {quote: 'Rest in natural great peace this exhausted mind,<br />Beaten helpless by karma and neurotic thoughts<br />Like the relentless fury of the pounding waves<br />In the infinite ocean of samsara.<br />Rest in natural great peace.', author: 'Nyoshul Khen Rinpoche'},
        {quote: 'Samsara and enlightenment\'s pervasive evenness is the view;<br />Within it, meditation is uncontrived settling in the natural state.<br />Conduct is to relax in non-activity.<br />Accept these as the keys of view, meditation, and conduct.', author: 'Dudjom Rinpoche'},
        {quote: 'The essence of retreat is setting up a boundary – and we are not actually talking about a physical boundary, but we are talking about a boundary of time, setting up a boundary between past and future, which ideally means we remain in presentness.', author: 'Dzongsar Khyentse Rinpoche'},
        {quote: 'A zen master\'s life is one continuous mistake.', author: 'Dogen Zenji'},
        {quote: 'The Buddhist notion of diligence is to delight in positive deeds.', author: 'Ringu Tulku Rinpoche'},
        {quote: 'Behold now, Bhikkhus, I exhort you: All compounded things are subject to decay. Strive with diligence!', author: 'Buddha'},
        {quote: 'Give up attachment to this life and let your mind become Dharma!', author: 'Dromtönpa'},
        {quote: 'In brief, taking your own mind as witness, make your life and practice one, and at the time of death, with no thought of anything left undone, do not be ashamed of yourself. This itself is the pith instruction of all practices.', author: 'Dudjom Rinpoche'},
        {quote: 'We work on ourselves in order to help others, but also we help others in order to work on ourselves.', author: 'Pema Chödrön'},
        {quote: 'Wherever you go you will find your teacher, as long as you have the eyes to see and the ears to hear.', author: 'Shunryu Suzuki'},
        {quote: 'If we always turn our mind to virtue, we always experience happiness as a result.', author: 'Lama Zopa Rinpoche'},
        {quote: 'My path is the path of stopping, the path of enjoying the present moment. It is a path where every step brings me back to my true home. It is a path that leads nowhere. I am on my way home. I arrive at every step.', author: 'Thich Nhat Hanh'},
        {quote: 'Some do not understand<br />that we must die,<br />But those who do realize this<br />settle their quarrels.', author: 'Buddha'},
        {quote: 'To give your sheep or cow a large spacious meadow is the way to control him.', author: 'Shunryu Suzuki'},
        {quote: 'Apply yourself to solitude. One who is given to solitude knows things as they really are.', author: 'Buddha'},
        {quote: 'Even though the meditator may leave the meditation, the meditation will not leave the meditator.', author: 'Dudjom Rinpoche'},
        {quote: 'If we can allow some space within our awareness and rest there, we can respect our troubling thoughts and emotions, allow them to come, and let them go. Our lives may be complicated on the outside, but we remain simple, easy, and open on the inside.', author: 'Tsoknyi Rinpoche'},
        {quote: 'To be aware of a single shortcoming within oneself is more useful than to be aware of a thousand in someone else.', author: '14th Dalai Lama'},
        {quote: 'Take your stand on the ultimate practice of the heart essence — samsara and nirvana are the display of awareness. Without distraction, without meditation, in a state of natural relaxation, constantly remain in the pure, all-penetrating nakedness of ultimate reality.', author: 'Dudjom Rinpoche'},
        {quote: 'Fear is a natural reaction to moving closer to the truth.', author: 'Pema Chödrön'},
        {quote: 'May our heart’s garden of awakening bloom with hundreds of flowers.', author: 'Thich Nhat Hanh'},
        {quote: 'The ultimate source of my mental happiness is my peace of mind. Nothing can destroy this except my own anger.', author: '14th Dalai Lama'},
        {quote: 'A moment of genuine contemplation of impermanence is the greatest offering among all offerings to the Buddhas.', author: 'Dzigar Kongtrül Rinpoche'},
        {quote: 'To attain buddhahood we must scatter this life’s aims and objects to the wind.', author: 'Milarepa'},
        {quote: 'Whatever happens, our commitment is to use it to awaken our heart. As one of the slogans says, ‘All activities should be done with one intention.’ That intention is to realize our connection with all beings.', author: 'Pema Chödrön'},
        {quote: 'Looking deeply into the wrong perceptions, ideas, and notions that are at the base of our suffering is the most important practice in Buddhist meditation.', author: 'Thich Nhat Hanh'},
        {quote: 'The Buddha told us to see the way things are and let go of our clinging to them. Take this feeling of letting go as your refuge.', author: 'Ajahn Chah'},
        {quote: 'The point is to care so keenly for others that you give rise to courage and determination to relieve them of their suffering. That is compassion.', author: '17th Karmapa'},
        {quote: 'Karma is not something complicated or philosophical. Karma means watching your body, watching your mouth, and watching your mind. Trying to keep these three doors as pure as possible is the practice of karma.', author: 'Lama Yeshe'},
        {quote: 'If you are going, remember bodhicitta<br />If you are sitting, remember bodhicitta<br />If you are lying down, remember bodhicitta<br />If you are standing, remember bodhicitta.', author: 'Khunu Rinpoche'},
        {quote: 'In brief, without being mindful of death, whatever Dharma practices you take up will be merely superficial.', author: 'Milarepa'},
        {quote: 'Bodhicitta is the electricity of spiritual practice. If it is cut, nothing works anymore. Animated with bodhicitta, all ordinary activity, all works in the world become a path to awakening.', author: 'Bokar Rinpoche'},
        {quote: 'I am present in front of anyone who has faith in me, just as the moon casts its reflection, effortlessly, in any vessel filled with water.', author: 'Padmasambhava'},
        {quote: 'In essence, discipline is to have a peaceful, self-controlled and altruistic mind.', author: 'Dilgo Khyentse Rinpoche'},
        {quote: 'If we cannot be happy in spite of our difficulties, what good is our spiritual practice?', author: 'Maha Ghosananda'},
        {quote: 'Shakyamuni Buddha said that everything, all the phenomena is circumstantial and the circumstance depends on motivation. So first of all I cant stress enough that we have to tune our motivation.', author: 'Dzongsar Khyentse Rinpoche'},
        {quote: 'When our beliefs are based on our own direct experience of reality and not on notions offered by others, no one can remove these beliefs from us.', author: 'Thich Nhat Hanh'},
        {quote: 'Do not discuss the faults of others. Realize that their “faults” are actually your own impure projections.', author: 'Jamgön Kongtrül Lodrö Thaye'},
        {quote: 'To study Buddhism is to study ourselves. To study ourselves is to forget ourselves.', author: 'Dogen Zenji'},
        {quote: 'Like molding dough in your hand, you can definitely turn your mind whichever way you want.', author: 'Lama Zopa Rinpoche'},
        {quote: 'The pathless path<br />is the path always under our feet<br />and since that path is always beneath us,<br />if we miss it, how stupid!', author: 'Longchenpa'},
        {quote: 'One should do nothing other than what is directly or indirectly of benefit to living beings.', author: 'Shantideva'},
        {quote: 'We feel our shell keeps us safe, but it crushes us and others, and keeps out light and sun.', author: 'Deshimaru'},
        {quote: 'To leave aside your own nature and search elsewhere is extremely deluded.', author: 'Saraha'},
        {quote: 'A hundred things may be explained, a thousand told,<br />But one thing only should you grasp.<br />Know one thing and everything is freed –<br />Remain within your inner nature, your awareness!', author: 'Padmasambhava'},
        {quote: 'Happiness doesn’t mean never feeling sad or distressed; rather, it is reflective of a general optimism toward ourselves and others.', author: 'Traleg Kyabgön Rinpoche'},
        {quote: 'The supreme thing to know is bodhicitta.<br />The supreme thing to learn is bodhicitta.<br />The supreme thing to practice is bodhicitta.<br />The supreme thing to meditate on is bodhicitta.', author: 'Khunu Rinpoche'},
        {quote: 'Enlightenment is not just chocolate at the end, in a lump. It is chocolate, chocolate, chocolate all the way!', author: 'Lama Yeshe'},
        {quote: 'As long as you seek for something, you will get the shadow of reality and not reality itself.', author: 'Shunryu Suzuki'},
        {quote: 'Fools attempt to avoid their suffering,<br />The wise enact their pain.<br />Drink the cup of sky-nectar<br />While others hunger for outward appearances.', author: 'Saraha'},
        {quote: 'You are Buddha in your essence. Nothing can corrupt that, nothing can shake that. That is real confidence.', author: 'Tai Situ Rinpoche'},
        {quote: 'Nonconceptual compassion<br />And the primordial nature of emptiness<br />Are inseparable in the nature of simplicity.<br />You should understand all dharmas like this.', author: 'Marpa'},
        {quote: 'Understanding is crucial in all human communication. When faced with people who are inflexible in their views, that is the time for you to be at your most flexible and accommodating, and to bring all your wisdom and compassion to bear.', author: '17th Karmapa'},
        {quote: 'Rest in a natural way like a small child.<br />Rest like an ocean without waves.<br />Rest within clarity like a candle flame.<br />Rest without self-concerns like a human corpse.<br />Rest unmoving like a mountain.', author: 'Milarepa'},
        {quote: 'To timeless buddhahood, basic total presence,<br />To unchanging spontaneity, the spacious vajra-heart,<br />To the nature of mind – natural perfection,<br />Constantly, simply being, we bow down.', author: 'Longchenpa'},
        {quote: 'The essence of Buddhism is kindness, compassion.', author: '14th Dalai Lama'},
        {quote: 'Radiate boundless love towards the entire world — above, below, and across — unhindered, without ill will, without enmity.', author: 'Buddha'},
        {quote: 'We can realize the beauty of our own inner nature when we stop manipulating everything that crosses our path as a way to fortify a sense of self. This is the practitioner’s approach to life.<Paste>', author: 'Dzigar Kongtrül Rinpoche'},
        {quote: 'Being wise selfish means taking a broader view and recognizing that our own long-term individual interest lies in the welfare of everyone. Being wise selfish means being compassionate.', author: '14th Dalai Lama'},
        {quote: 'Nothing ever goes away until it has taught us what we need to know.', author: 'Pema Chödrön'},
        {quote: 'Oh that my monk’s robes were wide enough<br />to gather up all the people<br />in this floating world.', author: 'Ryokan'},
        {quote: 'Death is as close as our breath.', author: 'Ajahn Chah'},
        {quote: 'There is enough for everybody’s needs, but not for everybody’s greed.', author: 'Mahatma Gandhi'},
        {quote: 'Until we have true devotion nothing deep is going to happen, that is for sure.', author: 'Tai Situ Rinpoche'},
        {quote: 'To amass a multitude of profound texts<br />Such as scriptures, commentaries and oral instructions,<br />Without practicing them, will be of no benefit at the time of death.<br />‘To watch your mind’ is my heart advice.', author: 'Longchenpa'},
        {quote: 'You can’t get stuck in space.', author: 'Chögyam Trungpa Rinpoche'},
        {quote: 'Spend some time alone every day.', author: '14th Dalai Lama'},
        {quote: 'To be diligent doesn’t mean to engage in various restless activities; it means to exert oneself in the means of leaving samsaric existence behind.', author: 'Padmasambhava'},
        {quote: 'If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.', author: 'Pema Chödrön'},
        {quote: 'There is nothing in this world that is worth losing a night’s sleep over, nothing.', author: 'Tai Situ Rinpoche'},
        {quote: 'Whatever living beings there may be — feeble or strong, long, stout, or of medium size, short, small, large, those seen or those unseen, those dwelling far or near, those who are born as well as those yet to be born — may all beings have happy minds.', author: 'Buddha'},
        {quote: 'The root of the entire dharma is mental rejection of the concerns of this life.', author: 'Jamgön Kongtrül Lodrö Thaye'},
        {quote: 'We don’t meditate to see heaven, but to end suffering.', author: 'Ajahn Chah'},
        {quote: 'Every second of this human life is more precious than skies of wish-granting jewels.', author: 'Lama Zopa Rinpoche'},
        {quote: 'The miracle is not to walk on water. The miracle is to walk on the green earth, dwelling deeply in the present moment and feeling truly alive.', author: 'Thich Nhat Hanh'},
        {quote: 'I feel that a sense of compassion is the most precious thing there is.', author: '14th Dalai Lama'},
        {quote: 'The deepest reasons to love yourself have nothing to do with anything outside you – not with your body or with others’ expectations of you. If you ground yourself in your own goodness, nothing will be able to damage your self-esteem.', author: '17th Karmapa'},
        {quote: 'Do not blame your past karma; instead, be someone who purely and flawlessly practices the Dharma. Do not blame temporary negative circumstances; instead, be someone who remains steadfast in the face of whatever circumstances may arise.', author: 'Dudjom Rinpoche'},
        {quote: 'If you make a real effort to take refuge sincerely in the Three Jewels, everything that opposes your practice will be transformed into favorable circumstances and your merit will grow unceasingly.', author: 'Patrul Rinpoche'},
        {quote: 'In the beginning I took the teacher as the teacher,<br />In the middle I took the scriptures as the teacher,<br />In the end I took my own mind as the teacher.', author: 'Shabkar'},
        {quote: 'The best offering one can make to the Buddhas and their teachers is to put the Dharma into practice. So it has been said by previous masters.', author: 'Dzongsar Khyentse Rinpoche'},
        {quote: 'If we believe in the continuity of mind, then love inconspicuously connects us to the ones we love with continuous positive energy, so that even tangible separations between people who love each other do not reduce the intangible power of love.', author: 'Thinley Norbu Rinpoche'},
        {quote: 'When you enter the path of Buddhist practice you’re ending an abusive relationship with yourself.', author: 'Mingyur Rinpoche'},
        {quote: 'Any brief moment, any time at all that one could use as an opportunity for dharma practice, one must use.', author: '16th Karmapa'},
        {quote: 'To be a meditator doesn’t simply mean to live in a cave; it means to train oneself in the true meaning [of the natural state].', author: 'Padmasambhava'},
        {quote: 'The goal of our renunciation should be to commit to what is beneficial for beings, and to what serves the cause of the dharma.', author: '17th Karmapa'},
        {quote: 'To give up yourself without regret is the greatest charity.', author: 'Bodhidharma'},
        {quote: 'Just as the ocean’s salty water<br />taken into the clouds turns sweet,<br />the stable mind works to benefit others,<br />the poison of objects turns into healing water.', author: 'Saraha'},
        {quote: 'Focus,<br />not on the rudenesses of others,<br />not on what they’ve done<br />or left undone,<br />but on what you<br />have and haven’t done<br />yourself.', author: 'Buddha'},
        {quote: 'Because of your smile, you make life more beautiful.', author: 'Thich Nhat Hanh'},
        {quote: 'When compassion awakens in your heart, you’re able to be more honest with yourself.', author: 'Mingyur Rinpoche'},
        {quote: 'Like birds landing on a tree top together, and then dispersing,<br />We are together for a very short time,<br />So it makes sense to live in harmony, in unconditional friendship.', author: 'Bokar Rinpoche'},
        {quote: 'Do not be superficial and inconstant, thinking that following the teacher and receiving his teachings will make you famous or that receiving only a few words of instruction and making a Dharma connection will suffice.', author: 'Dilgo Khyentse Rinpoche'},
        {quote: 'We often feel miserable and our world seems upside-down because we believe that external things will work out exactly as we plan and expect them to.', author: 'Lama Yeshe'},
        {quote: 'Continue practice into everyday life with a single meditation, always keeping in mind the intention to help others in all activities, eating, dressing, sleeping, walking, or sitting.', author: 'Jamgön Kongtrül Lodrö Thaye'},
        {quote: 'Anyone can build a house of wood and bricks, but the Buddha taught us that sort of home is not our real home. It’s a home in the world and it follows the ways of the world. Our real home is inner peace.', author: 'Ajahn Chah'},
        {quote: 'Meditation is not a competition.', author: 'Mingyur Rinpoche'},
        {quote: 'When you do something, you should burn yourself completely, like a good bonfire, leaving no trace of yourself.', author: 'Shunryu Suzuki'},
        {quote: 'A compassionate mind is a diligent mind.', author: 'Mingyur Rinpoche'},
        {quote: 'Each of you should examine your own mind, to see how you have squandered your lives on your needs and desires. Thoughtless maidens, get hold of your minds!', author: 'Mandarava'},
        {quote: 'My grandfather of mindfulness must watch constantly after this spoiled child of deluded mind to save him from disaster.', author: 'Thinley Norbu Rinpoche'},
        {quote: 'Our own life has to be our message.', author: 'Thich Nhat Hanh'},
        {quote: 'You offer joy and happiness to another person, and it reflects back into your own life.', author: '17th Karmapa'},
        {quote: 'The essence of the guru is wisdom: the perfectly clear and radiant state of mind in which bliss and the realization of emptiness are inseparably unified.', author: 'Lama Yeshe'},
        {quote: 'If one knows that everything is impermanent, one does not grasp, and if one does not grasp, one will not think in terms of having or lacking, and therefore one lives fully.', author: 'Dzongsar Khyentse Rinpoche'},
        {quote: 'Take your entire life as the only measure for the duration of your practice.', author: 'Dudjom Rinpoche'},
        {quote: 'It is impossible to liberate others while you are bound. It is possible to liberate others when you are free.', author: 'Buddha'},
        {quote: 'Whatever passes through your mind, don’t focus on it and don’t try to suppress it. Just observe it as it comes and goes.', author: 'Mingyur Rinpoche'},
        {quote: 'Be kind to yourself as you proceed along this journey. This kindness, in itself, is a means of awakening the spark of love within you and helping others to discover that spark within themselves.', author: 'Tsoknyi Rinpoche'},
        {quote: 'You must love in such a way that the person you love feels free.', author: 'Thich Nhat Hanh'},
        {quote: 'Meditation is a balancing act between attention and relaxation.', author: 'B. Alan Wallace'},
        {quote: 'An indispensable ingredient for spiritual maturation is the cultivation of fortitude: strength, forbearance, and patience.', author: 'B. Alan Wallace'},
        {quote: 'The mind that reaches out to other people, to the environment, to provide what it seems to lack itself, is a mind that is ignorant of its own resources for peace and happiness.', author: 'B. Alan Wallace'},
        {quote: 'Again and again, counteract the agitation and turbulence of the mind by relaxing more deeply, not by contracting the body or mind.', author: 'B. Alan Wallace'},
        {quote: 'I suggest that if you were able to focus your attention at will, you could actually choose the universe you appear to inhabit.', author: 'B. Alan Wallace'},
        {quote: 'Life is a flash of lightning in the dark of night. It is a brief time of tremendous potential.', author: 'B. Alan Wallace'},
        {quote: 'One of the most persistent of all delusions is the conviction that the source of our dissatisfaction lies outside ourselves.', author: 'B. Alan Wallace'},
        {quote: 'Do not look for faults in others, but look for faults in yourself, and purge them like bad blood.<br />Do not contemplate your own good qualities, but contemplate the good qualities of others, and respect everyone as a servant would.', author: 'Atisha'},
        {quote: 'The supreme learning is to realise the meaning of selflessness [absence of self]<br />The supreme spiritual discipline is to tame one\'s own mind.<br />The supreme good quality is great altruism.<br />The supreme oral instruction is to observe the mind at all times.<br />The supreme remedy is to know that nothing has any self-nature.<br />The supreme conduct is to be in disharmony with the world.<br />The supreme accomplishment is the continuous decrease of disturbing emotions.<br />The supreme sign of accomplishment is the continuous decrease of wishes and wants.<br />The supreme spiritual teacher is the one who exposes our hidden flaws.<br />The supreme instruction is the one that strikes those hidden flaws.<br />The supreme companions are mindfulness and alertness.<br />The supreme inspiration is enemies and hindrances, disease and suffering.<br />The supreme method is to be natural.<br />The supreme way of benefiting is to help others enter the Dharma.<br />The supreme benefit is a mind that turns towards the Dharma.', author: 'Atisha'},
        {quote: 'The best spiritual friend is one who attacks yours hidden faults.<br />The best instructions are the ones that hit those faults.<br />The best friends are mindfulness and vigilance.<br />The best incentives are enemies, obstacles, and sufferings of illness.<br />The best method is not to fabricate anything.', author: 'Atisha'},
        {quote: 'The qualities of Buddhahood are gained<br />Through living beings and Victorious Ones alike,<br />Why then do we respect the Victorious Ones<br />And not living beings in the same way?', author: 'Atisha'},
        {quote: 'Even if you can recite the whole Tripitaka by heart, even if you know the entire Dharma, if you don’t have the guru’s advice, there will be a gap between you and the Dharma when you practice.', author: 'Atisha'},
        {quote: 'One should live with few possessions<br />And dwell with one’s back turned<br />To the things that cause grasping.<br />Be as a wanderer in foreign lands<br />Taking food as it is found<br />Like the birds in migration.', author: 'Atisha'},
        {quote: 'In the company of others, guard your speech;<br />Whenever you are alone, guard your mind.', author: 'Atisha'},
        {quote: 'The greatest medicine is the emptiness of everything.', author: 'Atisha'},
        {quote: 'Those with little merit will not<br />Even wonder about these things.<br />But merely to entertain doubts<br />About saṃsāra will make it fall apart.', author: 'Aryadeva'},
        {quote: 'At first, turn away from non-virtue,<br />In the middle, dispel misconceptions of self,<br />Finally, go beyond all philosophical views—<br />One who understands this is wise indeed.', author: 'Aryadeva'},
        {quote: 'Whoever sees the nature of one thing<br />Is said to see the nature of everything.<br />For the emptiness of one thing<br />Is the emptiness of everything.', author: 'Aryadeva'}
        {quote: 'Have you ever, on earth or in the heavens,<br />Seen a being who was born but will not die?<br />Have you ever heard that this had happened?<br />Or even had suspicions that it might?', author: 'Aśvaghoṣa'},
        {quote: 'Great rishis with the five superknowledges,<br />Can fly far and wide through the sky,<br />Yet they will never reach a place<br />Where they might live and never die.', author: 'Aśvaghoṣa'},
        {quote: 'Trying to reach the great mansion<br />Of the authentic nature of reality<br />Without the steps of the authentic relative<br />Is not an approach the wise should take.', author: 'Bhavaviveka'},
        {quote: 'Love is the seed of this abundant harvest of buddhahood.<br />It is like the water which causes growth and expansion,<br />And it ripens into the state of lasting enjoyment,<br />Therefore at the outset I shall praise compassion!', author: 'Chandrakirti'},
        {quote: 'Firstly with the thought of “I”, they cling to self,<br />And then with “mine”, they grow attached to things,<br />Helplessly, they wander like a turning waterwheel—<br />To compassion for these beings, I bow down!', author: 'Chandrakirti'},
        {quote: 'Those who, when hearing about emptiness,<br />Are inspired with great joy again and again,<br />So that their eyes moisten with tears,<br />And the hairs on their body stand on end,<br />Possess the potential for complete awakening.<br />They are the proper vessels for these teachings,<br />To them one should teach the ultimate truth.', author: 'Chandrakirti'},
        {quote: 'The nature of mind is clear light,<br />Defilements are only adventitious.', author: 'Dharmakirti'},
        {quote: 'Introducing directly the face of rigpa in itself,<br />Decide upon one thing and one thing only,<br />Confidence directly in the liberation of rising thoughts.', author: 'Garab Dorje'},
        {quote: 'When, from out of the primordially pure Dharmadhatu,<br />Suddenly Rigpa arises, and with it there is an instantaneous recognition, it is<br />Like finding a precious jewel in the depths of the ocean,<br />No-one has created it - it is just the Dharmakaya', author: 'Garab Dorje'},
        {quote: 'Those who can distinguish between the two truths,<br />Will not be confused about the Buddha’s Words.<br />Gathering all the accumulations of merit and wisdom,<br />They will win perfection and reach the other shore.', author: 'Jñānagarbha'},
        {quote: 'He eats his father’s flesh while striking his own mother,<br />And cradles in his lap the enemy he killed,<br />The wife is gnawing at her husband’s bones.<br />Saṃsāra is enough to make you laugh out loud!', author: 'Kātyāyana'},
        {quote: 'Monks and learned ones,<br />Just as gold is burnt, cut and rubbed,<br />Examine my words carefully and <br />Do not accept them simply out of respect.', author: 'Buddha'},
        {quote: 'O Bhagavan, a bodhisattva should not train in many practices. O Bhagavan, if a bodhisattva keeps to one practice and learns it perfectly, he has all the Buddha’s teachings in the palm of his hand. What is that one practice? It is great compassion.', author: 'Buddha'},
        {quote: 'Like a star, hallucination, candle,<br />Magical illusion, dewdrop, bubble,<br />Dream, lightning or a cloud—<br />Know all compounded phenomena to be like this.', author: 'Buddha'},
        {quote: 'The mind is devoid of mind,<br />For the nature of mind is clear light.', author: 'Buddha'},
        {quote: 'Noble one, think of yourself as someone who is sick,<br />Of the Dharma as the remedy,<br />Of your spiritual teacher as a skilful doctor,<br />And of diligent practice as the way to recovery.', author: 'Buddha'},
        {quote: 'Form is emptiness; emptiness also is form.<br />Emptiness is no other than form,<br />Form is no other than emptiness.' author: 'Buddha'},
        {quote: 'Commit not a single unwholesome action,<br />Cultivate a wealth of virtue,<br />Tame completely this mind of ours—<br />This is the teaching of the buddhas.', author: 'Buddha'},
        {quote: 'When his time has come, even a king has to die,<br />And neither his friends nor his wealth can follow him.<br />So for us—wherever we stay, wherever we go—<br />Karma follows us like a shadow.', author: 'Buddha'},
        {quote: 'Do not disregard small misdeeds,<br />Thinking they are harmless,<br />Because even tiny sparks of flame,<br />Can set fire to a mountain of hay.', author: 'Buddha'},
        {quote: 'Do not disregard small positive acts,<br />Thinking they are without benefit,<br />Because even tiny drops of water,<br />Will eventually fill a large container.', author: 'Buddha'},
        {quote: 'Just as a drop of water that falls into the great ocean<br />Will never disappear until the ocean itself runs dry,<br />Merit totally dedicated to enlightenment<br />Will never disappear until enlightenment is reached.', author: 'Buddha'},
        {quote: 'Consciousness is impermanent.<br />Wisdom is permanent.', author: 'Buddha'},
        {quote: 'If the merit of bodhicitta<br />Were to take physical form,<br />Even the whole of space itself<br />Would not contain its vastness.', author: 'Buddha'},
        {quote: 'All beings are buddhas<br />But this is concealed by adventitious stains.<br />When their stains are purified, their buddhahood is revealed.', author: 'Hevajra Tantra'},
        {quote: 'Everything is circumstantial<br />And depends entirely on one’s aspiration.<br />Whatever prayers of aspiration people make<br />They will gain results accordingly.', author: 'Teaching on the Qualities of Mañjuśrī’s Pure Land'},
        {quote: 'Gather together all your thoughts in the proper way,<br />And listen with an exceptionally pure motivation.<br />A forgetful mind will receive no blessings<br />From Vajrasattva and the other buddhas of the three times.', author: 'Vajra Pinnacle Tantra'},
    ];

    return quotes[Math.floor(Math.random() * quotes.length)];
}
